from tkinter import *
raiz=Tk()
raiz.title("Ventana de prueba")
raiz.resizable(1,1)
raiz.iconbitmap("")
raiz.geometry("650x350")
raiz.config(bg="PaleTurquoise1")
miFrame=Frame()
miFrame.pack(fill=BOTH, expand=True)
miFrame.config(bg="PaleTurquoise2")
miFrame.config(width="650", height="350")
miFrame.config(bd="35")
miFrame.config(relief="sunken")
miFrame.config(cursor="hand2")
raiz.mainloop()
